name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: update shit
      run: sudo sed -i -e 's/archive.ubuntu.com\|security.ubuntu.com/old-releases.ubuntu.com/g' /etc/apt/sources.list
    - name: apt update
      run: sudo apt-get update
    - name: install dependencies
      run: sudo apt install -y --fix-missing make gcc qtmultimedia5-dev libogg-dev libopus-dev libgl1-mesa-dev build-essential libssl-dev qtbase5-dev qtchooser qt5-qmake qtbase5-dev-tools gcc-multilib qttools5-dev-tools
    - name: find file 
      run: find ./ -name '*.ts' -exec lrelease {} \;
    - name: qmake
      run: qmake ultracopier.pro
    - name: make
      run: make -j$(nproc)
    - uses: actions/upload-artifact@v3
      with:
        path: ./ultracopier*.*
